home/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('',views.home,name='home'),
    path('subscribe/',views.subscribe,name='subscribe'),
    path('search/',views.search,name='search'),
    path('notification/',views.notification,name='notification'),
    path('makeRead/',views.makeRead),
    # path('signup',views.signup,name='signup'),
    # path('login/',views.login,name='login'),        
    # path('<str:username>/',views.profile,name='profile')
 ]

job/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path("feed/",views.JobListView.as_view(),name="feed"),
    path('addjob/',views.addjob,name="addjob"),
    path("sport/",views.sport,name="sport"),
    # path("job_view/",views.job_view,name="job_view"),
    path("<int:pk>/",views.view_job ,name="job"),
    path("delete/<int:pk>/",views.delete_job ,name="delete_job"),
    path("update/<int:pk>/",views.update_job ,name="update_job"),
    path("apply/<int:pk>/",views.apply_job ,name="apply_job"),
    path('applied_job/',views.applied_job,name='applied_job'),
    path('company_application/',views.company_application,name='company_application'),
]

sih/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""sih URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from job import views as job_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('account/',include('account.urls')),
    path('job/',include('job.urls')),
    path('quiz/',include('quiz.urls')),
    path("searchJSON/",job_views.searchJSON)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
class Notification(models.Model):
    heading = models.CharField(max_length = 20)
    user = models.ForeignKey(to=User,on_delete = models.CASCADE)
    date_time = models.DateTimeField(auto_now_add = True)
    url = models.URLField(null=True)
    seen = models.BooleanField(default=False)
    def __str__(self):
        return self.heading

job/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import datetime
from PIL import Image 
from django.contrib.auth.models import User
from account.models import Company, Profile
# import io
# from django.core.files.uploadedfile import InMemoryUploadedFile

def get_image_filename(instance, filename):
    title = instance.job_title
    slug = slugify(title)
    return "jobImages/%s-%s-%s" % (slug, datetime.now(), filename)

class Job(models.Model):
    company = models.ForeignKey(Company,models.CASCADE)
    job_title = models.CharField(max_length=20)
    description = models.TextField(verbose_name="Job Description ")
    job_image = models.ImageField(upload_to=get_image_filename,verbose_name="Company Image")
    job_location_place = models.CharField(max_length=50,verbose_name="Job Location Place")
    about_company = models.TextField(verbose_name='About Company')
    join_date = models.DateField(verbose_name='Join Date') 
    location = models.CharField(max_length=50,verbose_name='Location')
    duration = models.CharField(max_length=50,verbose_name='Duration')
    post_date = models.DateField(verbose_name='Post Date')
    last_date_apply_by = models.DateField(verbose_name='Last Date Apply By')
    skills_required = models.TextField(verbose_name='Skills Required')
    who_can_apply = models.TextField(verbose_name='Who Can Apply')
    other_requirments = models.CharField(max_length=100,verbose_name='Other Requirments')
    salary = models.FloatField(verbose_name='Salary',default=0)
    applicants = models.ManyToManyField(Profile,blank=True,null= True)
    createation_date = models.DateTimeField(auto_now=True)
    mobile_number = models.CharField(max_length=12,default=0, verbose_name='Mobile No.')
    # number_of_openings = models.CharField(max_length=1000, verbose_name='Number Of Openings')
    number_of_openings = models.IntegerField(max_length=1000,default=0,verbose_name='Number Of Openings')



    def __str__(self):
        return self.job_title

def image_name(instance,filename):
    name = slugify(instance.name)
    return f"city_image/{name}.png"

class City(models.Model):
    name = models.CharField(max_length=10)
    image = models.ImageField(upload_to=image_name,default="john-schnobrich-FlPc9_VocJ4-unsplash.jpg")
    
    def __str__(self):
        return self.name    

    def save(self):
        super().save()  # saving image first
        img = Image.open(self.image.path) # Open image using self

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.image.path)  # saving image at the same path

home/views.py
from django.shortcuts import render, HttpResponse,redirect
from django.http import JsonResponse
from django.core import serializers


from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.models import User
from job.models import Job,City
import PIL
from  django.db.models import Q
from django.core.mail import send_mail
import socket
from .models import Notification
from account.views import is_company
# Creimportate your views here.
def home(request):
    if request.user.is_authenticated : # refresh
        user = request.user
        if is_company(user):
            job_detail = user.company.job_set.all()
        else:
            skill = user.profile.skill
            intrest = user.profile.intrest

            job_detail = Job.objects.filter(Q(job_title__icontains=skill) | Q(skills_required__icontains=skill) | Q(skills_required__icontains=intrest))
    else:
        job_detail = Job.objects.all().order_by("?")
    city_list = City.objects.all().order_by("-id")
    
    
    try:
        newC = job_detail[3:]
    except:
        newC = None      
    param = {
        # "jobCard": job_detail[:5],
        # "jobcrouselactive" : job_detail[:5],
        "jobNextCrousel" : newC,
        "cities" : city_list,
        "jobs": job_detail[:5],
        # "jobs_view": job_detail,

    }
    return render(request,'home.html',param)
def subscribe(request):
    email1 = request.GET["subscriber_email"]
    # path = request.GET["redirect"]
    # print(path)
    send_mail(
                    'Subject ',
                    'thanks for subscibe ',
                    'sih202021@gmail.com',
                    [ email1 ],
                    socket.getaddrinfo('localhost', 8080),
                    # fail_silently=False,
                )
    return redirect("/")

def search(request):
    if request.method=='POST':
        search1 = request.POST['search'] 
        if search1:
            match = Job.objects.filter(Q(job_title__icontains=search1) | Q(job_location_place__icontains=search1))
            
            if match:
                return render(request,'search.html', {'jobs':match})
            else:
                return render(request,'search.html')
        else:
            return redirect("/")
    else:
        return redirect("/")


def notification(request):
    return render(request,'notification.html')

def makeRead(request):
    pk = request.GET["id"]
    notify = Notification.objects.get(id=pk)
    notify.seen = True
    notify.save()
    return HttpResponse("done")


# profile based job recoommed logic

def proflieJobMatchig(request):
        get_skills = request.GET['skills_match'] 
        if get_skills:
            match_profile = Job.objects.filter(Q(skill__icontains=get_skills) | Q(intrest__icontains=get_skills))
            return JsonResponse(serializers.serialize(format="json",queryset=get_skills),safe=False)
            print(match_profile)
        else:
            return render(request,'home.html')

            # ab eske bas pas json wala kam karna ha bas

home/templates/apply_job.html
{% extends 'all.html' %}
{% load static %}
{% block content %}
<div class="" style="margin-top: 7%;"></div>
<div class="container">
    <h4>You have applied to this jobs !!    </h4>
        {% for job in request.user.profile.job_set.all reversed %}
        <a href="{% url 'job' job.id %}" class="text-decoration-none">
            <div class="media alert alert-success mt-3" >
                <img src="{{job.job_image.url}}" class="align-self-start mr-3" width="80px" alt="...">
                <div class="media-body">
                    <h5 class="mt-0"> {{job}}</h5>
                    <p>{{job.description|truncatewords:50 }}</p>
                    <p>you are seccessfully apply !! check your gmail</p>
                </div>
            </div>
        </a>
    {%endfor%}
</div>  
{% endblock content %}

home/templates/home.html
{% extends 'all.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/cityhover.css' %}">
{% endblock style %}
{% block content %}

<section style="padding-top: 80px;width: 100%;">
<div id="carouselExampleCaptions" class="carousel slide mt-0" data-ride="carousel" >
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
          <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner mt-0 p-2" style="border-radius: 15px 15px 15px 15px;">
          <div class="carousel-item active">
            <a href="#"><img src="{% static 'images/helloquence-OQMZwNd3ThU-unsplash.jpg' %}" class="d-block w-100" style="max-height: 650; border-radius: 15px 15px 15px 15px; " alt="..."></a>
            <div class="carousel-caption d-none d-md-block">
              <h5>First slide label</h5>
              <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            </div>
          </div>
          <div class="carousel-item">
            <a href="#"><img src="{% static 'images/ian-schneider-TamMbr4okv4-unsplash.jpg' %}" class="d-block w-100" style="max-height: 650; border-radius: 15px 15px 15px 15px; " alt="..."></a>
            <div class="carousel-caption d-none d-md-block">
              <h5>Second slide label</h5>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            </div>
          </div>
          <div class="carousel-item">
            <a href="#"><img src="{% static 'images/pic7.jpg' %}" class="d-block w-100" style="max-height: 650; border-radius: 15px 15px 15px 15px; " alt="..."></a>
            <div class="carousel-caption d-none d-md-block">
              <h5>Third slide label</h5>
              <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <!-- job cities -->
      <h2 class="container mt-5 d-flex justify-content-center">Job In Popular Cities</h2>
      <hr class="container" >

      <div class="card-columns mt-4 container">
        {% for city in cities %}
          <div class="overlay-auto " style="width: 100%; height: 30%;">
            <div class="hovereffect mt-4">
              <img class="img-responsive w-100 h-100" src="{{city.image.url}}"  alt="">
              <div class="overlay">
                 <h2>{{city.name}}</h2>
                 <a class="info" href="{% url 'feed' %}?city={{city.name}}">link here</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <hr class="container">

        <h2 class="container mt-5 d-flex justify-content-center">
            {% if user.profile %}
              Recommended Jobs
              {% else%}
            <!-- Uploaded Jobs -->
            {% endif %}
            </h2>
        <hr class="container">

           {% if jobs %}
            {% for job in jobs.all %}
            <div class="card container shadow mt-4 p-4" >
              <div class="d-flex align-item-center">
                <h3 class="card-title">{{ job.job_title }}</h3>
                  <img src= "{{job.job_image.url}}" width="100" height="100" class="centerCardImage ml-auto">
                   <!-- <div class="ml-auto">...</div> -->
              </div>
              <div class="">
                <h5 class="m-0 ">Company Name : {{ job.company }} </h5>
                <!-- <small class="text-muted">job.createation_date </small>
                <p class="text-muted m-0">330 People Applied</p> -->
            </div>
            <p class="mt-4 card-text" style="text-align: left;">Location : {{ job.job_location_place }} </p>
            <div class="form-group">
              <div class="container">
                <div class="row">
                  <div class="col-sm mt-2">
                    <label class="d-inline" for="exampleInputEmail1">joindate</label>
                    <small id="emailHelp" class="form-text ">{{ job.join_date }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Duration</label>
                    <small id="emailHelp" class="form-text ">{{ job.duration }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Salary</label>
                    <small id="emailHelp" class="form-text ">{{ job.salary }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Post Date</label>
                    <small id="emailHelp" class="form-text ">{{ job.post_date }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Last Date Apply By</label>
                    <small id="emailHelp" class="form-text ">{{ job.last_date_apply_by }}</small>
                  </div>
                </div>
              </div>
            </div>
              <div class="mt-0">
                  <p style="text-align: left;"> {{ job.location }} </p>
                  <a href="{% url 'job' job.id %}" class="btn btn-primary">view details</a>
              </div>
          </div>
          {% endfor %}
          {% else %}
            {% if user.profile %}
            <h5 class="container">Sorry No Jobs Available According To Your Skiils And Intrest</h5>
            {% else %}
            <p class="container">You have not Added any Job <a href="{% url "addjob" %}">Click Here </a> to add job. </p>
            {% endif %}  
          {% endif %}


<hr class="mt-5 container" >
  


</section>




{% endblock content %}

{% block script %}
<script src="{% static 'js/home.js' %} "></script>
{% endblock script %}

home/templates/notification.html
{% extends 'all.html' %}
{% load static %}
{% block content %}

<div class="" style="margin-top: 7%;"></div>

<div class="container">
    <h4>Notifications</h4>
    <p> You have new notifications</p>
        {% for notify in request.user.notification_set.all reversed %}
        <a href="{{notify.url}}" id={{notify.id}} onclick="return makeRead(id)" class="text-decoration-none ">
            <div class="media my-0 mt-3 alert alert-{% if notify.seen == False %}dark{%else%}light{%endif%}" >
                <!-- <img src="{{job.job_image.url}}" class="align-self-start mr-3" width="80px" alt="..."> -->
                <div class="media-body">
                    <p class="" style="float: right;"> {{notify.date_time}} </p>
                    <h5 class="m-0"> {{notify.heading}}..</h5>
                    <p class="mt-2">you are seccessfully apply !! check your gmail</p>
                    <!-- <p>you are seccessfully apply !! check your gmail </p> -->
                    <!-- <span style="float: right;">10:30pm</span> -->
                </div>
            </div>  
        </a><hr class="m-0" />

    {%endfor%}
    <div class="" style="margin-top: 15%;"></div>
</div>  
{% endblock content %}
{% block script %}
<script>
    function makeRead(id){
        fetch(`/makeRead/?id=${id}`)
        .then(res=>res.json())
        .then(data => console.log(data));
    }
</script>
{% endblock script %}

home/templates/search.html
{% extends 'all.html' %}
{% block content %}
<div class="" style="margin-top: 7%;"></div>

  {% if jobs %}
    {% for job in jobs.all %}
    <div class="card container shadow mt-4 p-4" >
              <div class="d-flex align-item-center">
                <h3 class="card-title">{{ job.job_title }}</h3>
                  <img src= "{{job.job_image.url}}" width="100" height="100" class="centerCardImage ml-auto">
                   <!-- <div class="ml-auto">...</div> -->
              </div>
              <div class="">
                <h5 class="m-0 "><a class="text-dark" href="#">Company Name : {{ job.company }}</a> </h5>
                <!-- <small class="text-muted">job.createation_date </small>
                <p class="text-muted m-0">330 People Applied</p> -->
            </div>
            <p class="mt-4">Location : {{ job.job_location_place }}</p>
            <div class="form-group">
              <div class="container">
                <div class="row">
                  <div class="col-sm mt-2">
                    <label class="d-inline" for="exampleInputEmail1">joindate</label>
                    <small id="emailHelp" class="form-text ">{{ job.join_date }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Duration</label>
                    <small id="emailHelp" class="form-text ">{{ job.duration }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Salary</label>
                    <small id="emailHelp" class="form-text ">{{ job.salary }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Post Date</label>
                    <small id="emailHelp" class="form-text ">{{ job.post_date }}</small>
                  </div>
                  <div class="col-sm mt-2">
                    <label for="exampleInputEmail1" class="d-inline">Last Date Apply By</label>
                    <small id="emailHelp" class="form-text ">{{ job.last_date_apply_by }}</small>
                  </div>
                </div>
              </div>
            </div>
              <div class="mt-0">
                  <p class="card-text"> {{ job.location }} </p>
                  <a href="{% url 'job' job.id %}" class="btn btn-primary">view details</a>
              </div>
          </div>
    {% endfor %}
{% else %}
<h5 class="container pb-5 text danger">No data found.....  </h5>
{% endif %}

{% endblock content %}