job/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path("feed/",views.JobListView.as_view(),name="feed"),
    path('addjob/',views.addjob,name="addjob"),
    path("sport/",views.sport,name="sport"),
    # path("job_view/",views.job_view,name="job_view"),
    path("<int:pk>/",views.view_job ,name="job"),
    path("delete/<int:pk>/",views.delete_job ,name="delete_job"),
    path("update/<int:pk>/",views.update_job ,name="update_job"),
    path("apply/<int:pk>/",views.apply_job ,name="apply_job"),
    path('applied_job/',views.applied_job,name='applied_job'),
    path('company_application/',views.company_application,name='company_application'),
]

sih/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""sih URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from job import views as job_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('account/',include('account.urls')),
    path('job/',include('job.urls')),
    path('quiz/',include('quiz.urls')),
    path("searchJSON/",job_views.searchJSON)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import datetime
from PIL import Image 
from django.contrib.auth.models import User
from account.models import Company, Profile
# import io
# from django.core.files.uploadedfile import InMemoryUploadedFile

def get_image_filename(instance, filename):
    title = instance.job_title
    slug = slugify(title)
    return "jobImages/%s-%s-%s" % (slug, datetime.now(), filename)

class Job(models.Model):
    company = models.ForeignKey(Company,models.CASCADE)
    job_title = models.CharField(max_length=20)
    description = models.TextField(verbose_name="Job Description ")
    job_image = models.ImageField(upload_to=get_image_filename,verbose_name="Company Image")
    job_location_place = models.CharField(max_length=50,verbose_name="Job Location Place")
    about_company = models.TextField(verbose_name='About Company')
    join_date = models.DateField(verbose_name='Join Date') 
    location = models.CharField(max_length=50,verbose_name='Location')
    duration = models.CharField(max_length=50,verbose_name='Duration')
    post_date = models.DateField(verbose_name='Post Date')
    last_date_apply_by = models.DateField(verbose_name='Last Date Apply By')
    skills_required = models.TextField(verbose_name='Skills Required')
    who_can_apply = models.TextField(verbose_name='Who Can Apply')
    other_requirments = models.CharField(max_length=100,verbose_name='Other Requirments')
    salary = models.FloatField(verbose_name='Salary',default=0)
    applicants = models.ManyToManyField(Profile,blank=True,null= True)
    createation_date = models.DateTimeField(auto_now=True)
    mobile_number = models.CharField(max_length=12,default=0, verbose_name='Mobile No.')
    # number_of_openings = models.CharField(max_length=1000, verbose_name='Number Of Openings')
    number_of_openings = models.IntegerField(max_length=1000,default=0,verbose_name='Number Of Openings')



    def __str__(self):
        return self.job_title

def image_name(instance,filename):
    name = slugify(instance.name)
    return f"city_image/{name}.png"

class City(models.Model):
    name = models.CharField(max_length=10)
    image = models.ImageField(upload_to=image_name,default="john-schnobrich-FlPc9_VocJ4-unsplash.jpg")
    
    def __str__(self):
        return self.name    

    def save(self):
        super().save()  # saving image first
        img = Image.open(self.image.path) # Open image using self

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            img.save(self.image.path)  # saving image at the same path

job/forms.py
from django import forms

from .models import *

class JobFrom(forms.ModelForm):
    class Meta:
        model = Job
        fields  = ["job_title", "description", "job_image", "join_date", "location", "duration", "post_date", "last_date_apply_by",
        "skills_required", "who_can_apply", "other_requirments", "salary","about_company","job_location_place","mobile_number","number_of_openings"]
        # widgets = {
        #     'name' : forms.TextInput(attrs={"class": "form-control"}),
        #     'description':  forms.Textarea(attrs={'class': 'form-control form-control-lg' }),
        #     'image' : forms.FileInput(attrs={"class": "form-control-file"}),
        #     'job_location_place':  forms.TextInput(attrs={'class': 'form-control form-control-lg' }),
        #     'location':  forms.TextInput(attrs={'class': 'form-control form-control-lg' }),
        #     'post_date':  forms.DateInput(attrs={'class': 'form-control form-control-lg' }),
        #     'duration':  forms.TextInput(attrs={'class': 'form-control form-control-lg' }),
        #     'last_date_apply_by':  forms.DateInput(attrs={'class': 'form-control form-control-lg' }),
        #     'about_company':  forms.Textarea(attrs={'class': 'form-control form-control-lg' }),
        #     'skills_required':  forms.Textarea(attrs={'class': 'form-control form-control-lg' }),
        #     'who_can_apply':  forms.Textarea(attrs={'class': 'form-control form-control-lg' }),
        #     'other_requirments':  forms.TextInput(attrs={'class': 'form-control form-control-lg' }),
        #     'salary':  forms.TextInput(attrs={'class': 'form-control form-control-lg' }),
        #     'join_date':  forms.DateInput(attrs={'class': 'form-control form-control-lg' }),
        # }

job/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.http import JsonResponse
from django.core import serializers

from .models import Job
from .forms import *
from django.core.mail import send_mail
import socket
from socket import *    
from django.views.generic.list import ListView
from  django.db.models import Q
from account.views import is_company,is_user_form_filled
from home.models import Notification


class JobListView(ListView):
    model = Job
    context_object_name = "jobs"
    template_name  = "job_feed.html"
    paginate_by = 10
    def get_queryset(self):
        word = self.request.GET.get("city","")
        cat = self.request.GET.get("catagory","")
        if word:
            word  = word.lower()
        return Job.objects.filter(Q(job_location_place__icontains= word) | Q(job_title= word) | Q(job_title= cat) ) 

def view_job(request,pk):
    job = Job.objects.get(id =pk)
    param = {
        "job" : job
    }
    return render(request,"job.html",param)

def addjob(request):
    if request.method == "POST":
        form  = JobFrom(request.POST,request.FILES)
        # print(forms)
        if form.is_valid():
            # print("form valid")
            job = form.save(commit=False)
            job.company = request.user.company
            job.save()
            return redirect("/")
    job_from = JobFrom()
    return render(request,'addJob.html',{"job_form": job_from})

def update_job(request,pk): 
    job = Job.objects.get(id=pk)
    if request.method == "POST":
        form  = JobFrom(request.POST,request.FILES,instance=job )    
        if form.is_valid():
            # print("form valid")
            job = form.save(commit=False)   
            job.company = request.user.company
            job.save()
            return redirect("job",job.id)
    job_from = JobFrom(instance=job)
    return render(request,'addJob.html',{"job_form": job_from,"job":job,"im_updating":True})


def sport(request):
    return render(request,"sport.html")

def delete_job(request,pk): 
    if is_company(request.user): 
        job = Job.objects.get(id=pk)
        job.delete()
        return redirect("profile",request.user.username,)

def apply_job(request,pk):
    if not request.user.is_authenticated:
        return HttpResponse("<h1>You are not Autherized Go Back Login First!!</h1><br/> <h1>Accss is Denied</h1>")
        
    user = request.user
    if not is_company(user):
        if not is_user_form_filled(user):
            return redirect("modify_profile")
        else:
            job = Job.objects.get(id=pk)
            job.applicants.add(user.profile)
            job.save()
            Notification.objects.create(
                heading = f"You have Applied For {job.job_title}",
                user = request.user,
                url = f"/job/{job.id}" 
            ).save() 
            send_mail(
                'Congratulations',
                'Hi ' + user.first_name  +'''  Congratulations on making your first application on . We are happy to have you onboard with us! \n
                Now that you have moved a step closer towards securing an job, lets get you acquainted to some 
                of the basic and important guidelines to be followed on job-\n 
                1.job on company are always free. You DO NOT have to pay anything in order to secure an job through us. Please Note: 
                If an organization asks you to pay a security deposit or a fee for the job then,
                please bring this to our attention by visiting the Help Center, so that we can look into
                it and take necessary actions.\n
                2. Please do not accept the job (except NGOs or Campus Ambassador programs) 
                if you are directly hired (without an interview or submitting an assignment) for the job.
                The general process is that the employer takes an interview or gives an assignment. And, on 
                the basis of your performance in that, you are selected for the job or proceed to the next r
                ound of interview. If you do get hired directly then, please bring it to our notice by dropping
                a query from the Help Center.\n
                3. Always ask for an offer letter or an email that confirms your 
                hiring and mentions the terms and conditions of jon from the employer before starting your job. 
                In a campus ambassador program, generally, employers do not give an offer letter. If you receive
                an email with all the details of the program, then that works as well.\n
                4. Never leave the job after accepting the offer extended by the employer. In case of an emergencyor any unavoidable c
                ircumstance you are not able to continue, then please write to the employer regarding 
                the same and elaborate in detail the entire scenario to them. This gesture would help them 
                understand the scenario as well as help them move on to hire the next best candidate quickly.
                \n Great! You are all caught up now and have familiarised yourself with the  general community guidelines. To read the guidelines in detail.\n 
                Now, as your application has been shared with the employer, you must be wondering about the next steps. For th
                at, you need to wait for a few days. If the employer likes your application, he/she will
                get in touch with you within 1-2 weeks and give you further details regarding the job.
                You can also check your application status by logging into your gmail account. \n Tip
                - In case you do not get any response or a status update regarding your application fro
                m the employer within 1-2 weeks of applying and your application status remains Applied, Seen or Under Review then, 
                it is best that you apply for various other jobs that are available on the platform. 
                You may also go through this article to know how you can improve your applications which will, in turn, 
                increase your chances of getting hired.\n All the very best! ''' ,
                'sih202021@gmail.com',
                [ user.email ],
                fail_silently=False,
                ) 
            return redirect("applied_job")
    else:
        return HttpResponse("<h1>You are not Autherized<h1> <br/> <h1>Accss is Denied</h1>")
    return render(request,"job_view.html")

def applied_job(request):
    return render(request, 'apply_job.html')

def company_application(request):
    return render(request, "company_application.html")

def searchJSON(request):
    
    search1 = request.GET['search'] 
    if search1:
        match = Job.objects.filter(Q(job_title__icontains=search1) | Q(job_location_place__icontains=search1))
        return JsonResponse(serializers.serialize(format="json",queryset=match),safe=False)
        print(match)
    else:
        return redirect("/")

job/templates/addjob.html
{% extends 'all.html' %}
{% block content %}
<div class="container" style="margin-top: 5%;">
<h1 style="margin-top: 50px;">Add job</h1>
<small>hello world..</small>
</div>
<form action="" method = "POST" enctype="multipart/form-data">{% csrf_token%}
<!-- <div class="container mt-3">
  {{job_form}} 
  </div> -->
  <div class="container mt-5">
    <!-- company image -->
    <!-- <h1 class="mt-5">add job form</h1> -->
    <!-- company name -->
      <div class="row">
        <div class="col">
          <fieldset disabled>
          <label for="formGroupExampleInput">Company name</label>
        <input class="form-control form-control-lg disabled" id="id_name" name="name" type="text" placeholder="" value="{{request.user}}">
      </fieldset>
        </div>
        <div class="col">
          <label for="formGroupExampleInput">job title</label>
        <input class="form-control form-control-lg" type="text" value="{{job.job_title }} "placeholder="" id="id_job_title" name="job_title" required >
        </div>
      </div>

      <div class="form-group mt-4">
        <label for="exampleFormControlFile1">Company image</label>
        <input type="file" class="form-control-file" id="id_job_image" name="job_image" id="id_image" accept="image/*" >
      </div>

    <!-- company description -->
    <div class=" mt-4">
      <label for="exampleFormControlTextarea1">job discription</label>
      <textarea class="form-control" rows="5" id="id_description" name="description" required>{{job.description}}</textarea>
    </div> 

    <div class="row mt-4">
      <div class="col">
        <label for="formGroupExampleInput">Job Location Place</label>
      <input class="form-control form-control-lg" type="text" placeholder="" id="id_job_location_place" name="job_location_place" value="{{job.job_location_place}}" required>
      </div>
      <div class="col">
        <label for="formGroupExampleInput">Mobile No.</label>
      <input class="form-control form-control-lg" type="text" placeholder="" name="mobile_number" value="{{job.mobile_number}}" id="id_mobile_number" required>
      </div>
    </div>

    <div class="row mt-4">

      <div class="col">
        <div class=" form-row align-items-center">
          <div class="col-auto my-1">
            <label class="mr-sm-2" for="inlineFormCustomSelect">Location</label>
            <select class="custom-select mr-sm-2"  name="location" id="id_location" required value="{{job.location}}">
              <option selected>Choose...</option>
              <option selected>Full Time</option>
              <option selected>Part Time</option>
              <option selected>Work From Home</option>
            </select>
          </div>
        </div>
      </div>
      <!-- <div class="col">
        <div class=" form-row align-items-center">
          <div class="col-auto my-1">
            <label class="mr-sm-2" for="inlineFormCustomSelect">Location</label>
            <select class="custom-select mr-sm-2" id="inlineFormCustomSelect" id="id_location"  name="location">
              <option selected>Choose...</option>
              <option value="1">Full Time </option>
              <option value="2">Part Time</option>
              <option value="3">Work From Home</option>
            </select>
          </div>
        </div>
      </div> -->

      <div class="col">
        <div class=" form-row align-items-center">
          <div class="col-auto my-1">
            <label class="mr-sm-2" for="inlineFormCustomSelect">Duration</label>
            <select class="custom-select mr-sm-2"  name="duration" id="id_duration" required value={{job.duration}}>
              <option selected>Choose...</option>
              <option selected>1 Months</option>
              <option selected>2 Months</option>
              <option selected>3 Months</option>
              <option selected>4 Months</option>
              <option selected>5 Months</option>
              <option selected>6 Months</option>
              <option selected>7 Months</option>
              <option selected>8 Months</option>
              <option selected>9 Months</option>
              <option selected>10 Months</option>
              <option selected>11 Months</option>
              <option selected>1 Year</option>
              <option selected>1.5 Year</option>
              <option selected>2 Year</option>
              <option selected>2.5 Year</option>
              <option selected>3 Year</option>
            </select>
          </div>
        </div>
      </div>
    </div>    


    <!-- <div class="mt-4">
    <label for="exampleFormControlTextarea1">About Company</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" ></textarea>
    </div> -->
    <div class="mt-4">
      <label for="exampleFormControlTextarea1">About Company</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="about_company" id="id_who_can_apply" required>{{job.about_company}}</textarea>
    </div>

    <div class="mt-4">
      <label for="exampleFormControlTextarea1">Skills Required</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="skills_required" id="id_skills_required" required>{{job.skills_required}}</textarea>
    </div>

    <!-- <div class="container mt-4">
      <label for="formGroupExampleInput">Who Can Apply</label>
      <input class="form-control form-control" type="text" placeholder="">
    </div> -->
    <div class="mt-4">
      <label for="exampleFormControlTextarea1">Who Can Apply</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="who_can_apply" id="id_who_can_apply" required>{{job.who_can_apply}}</textarea>
    </div>
    
    <div class="mt-4">
      <label for="exampleFormControlTextarea1">Other Requirment</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="other_requirments" id="id_other_requirments" required>{{job.other_requirments}}</textarea>
    </div>

    <div class="row mt-4">
      <div class="col">
        <label for="formGroupExampleInput">Post Date</label>
      <input class="form-control form-control-lg" type="date" placeholder="year-month-date" name="post_date" value = "{{job.post_date}}" id="id_post_date" required>
      </div>
      <div class="col">
        <label for="formGroupExampleInput">Last Date Apply By</label>
      <input class="form-control form-control-lg" type="date" placeholder="year-month-date" name="last_date_apply_by" value="{{job.last_date_apply_by}}" id="id_last_date_apply_by" required> 
      </div>
    </div>

    <div class="row mt-4">
      <div class="col">
        <label for="formGroupExampleInput">Salary</label>
      <input class="form-control form-control-lg" type="text" placeholder="" name="salary" value="{{job.salary}}" id="id_salary" required> 
      </div>
      <div class="col">
        <label for="formGroupExampleInput">Join Date</label>
      <input class="form-control form-control-lg" type="date" placeholder="year-month-date" name="join_date" value="{{job.join_date}}" id="id_join_date" required>
      </div>
    </div>
    
    <div class="row mt-4">
      <div class="col">
        <label for="formGroupExampleInput">Number Of Openings</label>
      <input class="form-control form-control-lg" type="number" placeholder="" name="number_of_openings" value="{{job.number_of_openings}}" id="id_number_of_openings" required>
      </div> 
    </div>


    <div class="form-group mt-5">
        <button type="submit" class="btn btn-primary " data-toggle="button" aria-pressed="false">
          Upload job
        </button>
    </div>
  </div>
  </form>

  <!-- {{job_form}} -->
{% endblock content %}
{% block script %}
<script>
  function setDate(date) {
    return new Date(date).toJSON().substring(0,10);    
  }
  $("#id_post_date").val(setDate("{{job.post_date}}")) 
  $("#id_last_date_apply_by").val(setDate("{{job.last_date_apply_by}}"))
  $("#id_join_date").val(setDate("{{job.join_date}}"))
</script>
{% endblock script %}

job/templates/company_application.html
{% extends 'all.html' %}
{% load static %}
{% block content %}
<div class="" style="margin-top: 7%;"></div>
<div class="container">
    <div class="mt-5 mb-4">
        <h4> Company upload job  </h4> 
        <hr>
        {% for job in request.user.company.job_set.all reversed %}
        <div class="card container shadow mt-2 p-4" >
          <div class="d-flex align-item-center">
            <h3 class="card-title">{{job.job_title}}</h3>
            <img src= "{{job.job_image.url}}" width="100" height="100" class="centerCardImage ml-auto">
            <!-- <div class="ml-auto">...</div> -->
          </div>
          <div class="mt-4">
            <h5 class="m-0 "><a class="text-dark" href="#">Company Name : {{job.company}}</a> </h5>
                <!-- <small class="text-muted">job.createation_date </small>
                <p class="text-muted m-0">330 People Applied</p> -->
          </div>
          <p class="mt-4 card-text" style="text-align: left;">Location : {{ job.job_location_place }} </p>
          <div class="form-group">
            <div class="container">
              <div class="row">   
                <div class="col-sm mt-2">
                  <label class="d-inline" for="exampleInputEmail1">joindate</label>
                  <small id="emailHelp" class="form-text ">{{job.join_date}}</small>
                </div>
                <div class="col-sm mt-2">
                  <label for="exampleInputEmail1" class="d-inline">Duration</label>
                  <small id="emailHelp" class="form-text ">{{job.duration}} month</small>
                </div>
                <div class="col-sm mt-2">
                  <label for="exampleInputEmail1" class="d-inline">Salary</label>
                  <small id="emailHelp" class="form-text ">{{job.salary}}</small>
                </div>
                <div class="col-sm mt-2">
                  <label for="exampleInputEmail1" class="d-inline">Post Date</label>
                  <small id="emailHelp" class="form-text ">{{job.post_date}}</small>
                </div>
                <div class="col-sm mt-2">
                  <label for="exampleInputEmail1" class="d-inline">Last Date Apply By</label>
                  <small id="emailHelp" class="form-text ">{{job.last_date_apply_by}}</small>
                </div>
              </div>
            </div>
          </div>
          <div class="mt-0">
            <p style="text-align: left;"> {{job.location}} </p>
            <a href="{% url 'job' job.id %}" class="btn btn-success">View</a>
            <a href="{% url 'update_job' job.id %}" class="btn btn-primary">Update</a>
            <a href="{% url 'delete_job' job.id %}" class="btn btn-danger" style="float: right;">Delete</a>
            <!-- <button style="float: right;" class="btn btn-primary" type="submit">Update</button> -->
            <!-- <button style="float: right;" class="btn btn-danger mr-4" type="submit">Delete</button> -->
          </div>
        </div>
        {% endfor %}
      </div>
</div>  
{% endblock content %}

job/templates/job.html
{% extends 'all.html' %}
{% load static %}
{% block title %} {{blog.heading}} {% endblock title %}
{% block content %}
<div style="padding: 30px;"></div>

<section>
    <div class="jumbotron pt-4">
        <div class="card shadow container col-md-7">
            <h5 class="card-header d-flex"> 
                <i class="material-icons ml-2">loyalty</i>
                {% if request.user.id  %}
                <a href="#" class="text-danger ml-3" id="delete-project"
                    onclick="return confirm('Are you sure ?')">
                    <i class="ml-auto material-icons mx-2">delete</i>
                </a>
                <a href="" class="text-dark ml-3"><i
                    class="material-icons">edit</i></a>

                {% endif %}
            </h5>
            <div class="card-body overflow-auto ">
                <!-- <h5 class="card-title">{{job.name}}</h5>
              <p class="card-text">{{job.description|safe}}</p> -->
              <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
              <div class="card-body overflow-auto ">  
                <div class="d-flex align-item-center">
                  <h3 class="card-title">{{ job.job_title}}</h3>
                    <img src="{{ job.job_image.url }}" width="100" height="100" class="centerCardImage ml-auto">
                </div>
                  <h5 class="m-0 "><a class="text-dark" style="text-decoration: none;" href="#">Company Name : {{ job.company }}</a> </h5>
              <p class="mt-4">Location : {{ job.job_location_place }}</p>
              <div class="form-group">
                <div class="container">
                  <div class="row">
                    <div class="col-sm mt-2">
                      <label class="d-inline" for="exampleInputEmail1">joindate</label>
                      <small id="emailHelp" class="form-text ">{{ job.join_date }}</small>
                    </div>
                    <div class="col-sm mt-2">
                      <label for="exampleInputEmail1" class="d-inline">Duration</label>
                      <small id="emailHelp" class="form-text ">{{ job.duration }}</small>
                    </div>
                    <div class="col-sm mt-2">
                      <label for="exampleInputEmail1" class="d-inline">Salary</label>
                      <small id="emailHelp" class="form-text ">{{ job.salary }}</small>
                    </div>
                    <div class="col-sm mt-2">
                      <label for="exampleInputEmail1" class="d-inline">Post Date</label>
                      <small id="emailHelp" class="form-text ">{{ job.post_date }}</small>
                    </div>
                    <div class="col-sm mt-2">
                      <label for="exampleInputEmail1" class="d-inline">Last Date Apply By</label>
                      <small id="emailHelp" class="form-text ">{{ job.last_date_apply_by }}</small>
                    </div>
                  </div>
                </div>
              </div>
                <div class="mt-0">
                    <p class="card-text"> {{ job.location }} </p>

                    <div class=" mt-5">
                        <label for="exampleInputEmail1" class="d-inline">About Company :</label>
                        <small id="emailHelp" class="form-text ">{{ job.about_company }}
                        </small>
                      </div>

                      <div class=" mt-5">
                        <label for="exampleInputEmail1" class="d-inline">Mobile No.</label>
                        <small id="emailHelp" class="form-text ">{{ job.mobile_number }}
                        </small>
                      </div>

                      <div class=" mt-5">
                        <label for="exampleInputEmail1" class="d-inline">Job Discription :</label>
                        <small id="emailHelp" class="form-text ">{{ job.description }}
                        </small>
                      </div>
                      
                      <div class=" mt-4">
                        <label for="exampleInputEmail1" class="d-inline">Who Can Apply : Those Condidates Are Apply</label>
                        <small id="emailHelp" class="form-text ">{{ job.who_can_apply }}
                        </small>
                      </div>

                      <div class=" mt-4">
                        <label for="exampleInputEmail1" class="d-inline">Skills Required</label>
                        <small id="emailHelp" class="form-text ">{{ job.skills_required }}
                        </small>
                      </div>

                      <div class=" mt-4">
                        <label for="exampleInputEmail1" class="d-inline">Other Requirments</label>
                        <small id="emailHelp" class="form-text ">  {{ job.other_requirments }}
                        </small>
                      </div>

                      <div class=" mt-4">
                        <label for="exampleInputEmail1" class="d-inline">Number Of Openings</label>
                        <small id="emailHelp" class="form-text ">  {{ job.number_of_openings }}
                        </small>
                      </div>

                    <a href="{% url 'apply_job' job.id %}" type="submit" class="btn btn-primary btn-lg btn-block mt-5 mb-5" style="border-radius: 5rem;">Apply</a>
                    
                </div>
        </div>
            </div>
            <div class="card-footer text-muted d-flex">
                <span>{{jobcreateation_date.creation_date}}</span>
                <span class="ml-auto text-light p-1 bg-dark rounded">{{blog.writer.first_name}} {{blog.writer.last_name}}</span>
            </div>
        </div>
    </div>
</section>
{% endblock content %}