job/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path("feed/",views.JobListView.as_view(),name="feed"),
    path('addjob/',views.addjob,name="addjob"),
    path("sport/",views.sport,name="sport"),
    # path("job_view/",views.job_view,name="job_view"),
    path("<int:pk>/",views.view_job ,name="job"),
    path("delete/<int:pk>/",views.delete_job ,name="delete_job"),
    path("update/<int:pk>/",views.update_job ,name="update_job"),
    path("apply/<int:pk>/",views.apply_job ,name="apply_job"),
    path('applied_job/',views.applied_job,name='applied_job'),
    path('company_application/',views.company_application,name='company_application'),
]

quiz/urls.py
from django.urls import path, re_path
# from views import MyQuizListAPI, QuizListAPI, QuizDetailAPI, SaveUsersAnswer, SubmitQuizAPI
from . import views

urlpatterns = [
	path("", views.MyQuizList.as_view(),name="myQuizList"),
	path("quize/<slug>/", views.QuizDetail.as_view(),name="quizDetail"),
	path("save-answer/", views.saveUserAnswer,name= "saveUserAnswer"),
	path("result/<slug>/", views.show_result,name="result"),
	path("instruction/", views.instruction,name= "instruction"),
	# re_path(r"quizzes/(?P<slug>[\w\-]+)/$", QuizDetailAPI.as_view()),
	# re_path(r"quizzes/(?P<slug>[\w\-]+)/submit/$", SubmitQuizAPI.as_view()),
]

sih/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""sih URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from job import views as job_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('account/',include('account.urls')),
    path('job/',include('job.urls')),
    path('quiz/',include('quiz.urls')),
    path("searchJSON/",job_views.searchJSON)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/models.py
from django.db import models

# Create your models here.
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify



class Quiz(models.Model):
	name = models.CharField(max_length=100)
	description = models.CharField(max_length=70)
	image = models.ImageField()
	slug = models.SlugField(blank=True)
	roll_out = models.BooleanField(default=False)
	timestamp = models.TimeField()
	timestamp_str = models.CharField(max_length = 10,null=True,blank=True)
	class Meta:
		ordering = ['timestamp',]
		verbose_name_plural = "Quizzes"
		
	def __str__(self):
		return self.name

	def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
		self.timestamp_str = self.timestamp
		quiz = super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
		return quiz
		

class Question(models.Model):
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	label = models.CharField(max_length=1000)
	order = models.IntegerField(default=0)

	def __str__(self):
		return self.label


class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	label = models.CharField(max_length=100)
	is_correct = models.BooleanField(default=False)

	def __str__(self):
		return self.label


class QuizTaker(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	score = models.IntegerField(default=0)
	completed = models.BooleanField(default=False)
	date_finished = models.DateTimeField(null=True)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.email


class UsersAnswer(models.Model):
	quiz_taker = models.ForeignKey(QuizTaker, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)

	def __str__(self):
		return self.question.label


@receiver(pre_save, sender=Quiz)
def slugify_name(sender, instance, *args, **kwargs):
	instance.slug = slugify(instance.name)

quiz/views.py
from django.shortcuts import render,HttpResponse,redirect

# # Create your views here.
from django.db.models import Q
from django.shortcuts import get_object_or_404
# # from rest_framework import generics, permissions, status
# # from rest_framework.response import Response
from quiz.models import Answer, Question, Quiz, QuizTaker, UsersAnswer
from django.views import generic
# # from quiz.serializers import MyQuizListSerializer, QuizDetailSerializer, QuizListSerializer, QuizResultSerializer, UsersAnswerSerializer
from account.views import is_company


class MyQuizList(generic.ListView):
    model = Quiz
    queryset = Quiz.objects.all()
    context_object_name = 'quiz_list'   
    template_name = "quiz.html"  
    
    def get_queryset(self, *args, **kwargs):
        queryset = Quiz.objects.filter(quiztaker__user=self.request.user)
        user = self.request.user
        if is_company(user):
            return HttpResponse("Invalid User !!")
        else:
            query = user.profile.skill
            intrest = user.profile.intrest
            queryset = queryset.filter(
				Q(name__icontains=query) |
				Q(description__icontains=query) |
				Q(name__icontains=intrest) |
				Q(description__icontains=intrest) 
			).distinct()
            return queryset
class QuizDetail(generic.DetailView):
    model = Quiz
    template_name = "quiz_detail.html"
    slug_url_kwarg = 'slug'
    context_object_name = 'quiz' 
    
    def get_context_data(self, **kwargs):
        slug = self.kwargs["slug"]
        quiz = get_object_or_404(Quiz, slug=slug)
        last_question = None
        obj, created = QuizTaker.objects.get_or_create(user=self.request.user, quiz=quiz)
        # print(quiz,"adsjiofsjgifodgjioj")
        if created:
            # print("YES!!!")
            for question in Question.objects.filter(quiz=quiz):
                UsersAnswer.objects.create(quiz_taker=obj, question=question)
        
        kwargs["quiztaker"] = obj
        # print(kwargs)
        return super().get_context_data(**kwargs)
 

def saveUserAnswer(request):
    if request.method == "POST":
        data = request.POST.get("allData",None)
        quiztaker_id = request.POST.get("quizTaker",None)
        data = eval(data)

        if data != {} and quiztaker_id is not None:
            quiztaker = get_object_or_404(QuizTaker, id=quiztaker_id)
            
            if quiztaker.completed:
                return HttpResponse("This quiz is already complete. you can't answer any more questions")

            for question_id,answer_id in data.items():
                question = get_object_or_404(Question, id=question_id)
                answer = get_object_or_404(Answer, id=answer_id)
                
                obj = get_object_or_404(UsersAnswer, quiz_taker=quiztaker, question=question)
                obj.answer = answer
                obj.save()
                # print(obj,question,answer,"models") #done
            quiztaker.completed = True
            correct_answers = 0
            
            for users_answer in UsersAnswer.objects.filter(quiz_taker=quiztaker):
                answer = Answer.objects.get(question=users_answer.question, is_correct=True)
                print("Right_ans",answer)
                print("Your ANS",users_answer.answer)
                if users_answer.answer == answer:
                    correct_answers += 1
                    
            quiztaker.score = int(correct_answers / quiztaker.quiz.question_set.count() * 100)
            print(quiztaker.score)
            quiztaker.save()

            return redirect("result",quiztaker.quiz.slug)

        else:
            return render(request,"result.html")

    else:
        return HttpResponse("Plese select Options")

def  show_result(request,slug):
    quiz = get_object_or_404(Quiz, slug=slug)
    obj, created = QuizTaker.objects.get_or_create(user=request.user, quiz=quiz)
    # if created:
    print(obj.score)
    mark = obj.score
    if mark >= 50 :
        is_pass = True
    else : 
        is_pass = False
    return render(request,"result.html",{
            "quiz_taker" : obj,
            "is_pass" : is_pass
        })
def instruction(request):
    slug = request.GET.get("quiz",None)
    if slug:
        return render(request,"instruction.html",{"slug":slug})
    return HttpResponse("Invalid Exam Selection <b>Go Back</b>!! ")
# class SubmitQuizAPI(generics.GenericAPIView):
# 	serializer_class = QuizResultSerializer
# 	permission_classes = [
# 		permissions.IsAuthenticated
# 	]

# 	def post(self, request, *args, **kwargs):
# 		quiztaker_id = request.data['quiztaker']
# 		question_id = request.data['question']
# 		answer_id = request.data['answer']

# 		quiztaker = get_object_or_404(QuizTaker, id=quiztaker_id)
# 		question = get_object_or_404(Question, id=question_id)

# 		quiz = Quiz.objects.get(slug=self.kwargs['slug'])

# 		if quiztaker.completed:
# 			return Response({
# 				"message": "This quiz is already complete. You can't submit again"},
# 				status=status.HTTP_412_PRECONDITION_FAILED
# 			)

# 		if answer_id is not None:
# 			answer = get_object_or_404(Answer, id=answer_id)
# 			obj = get_object_or_404(UsersAnswer, quiz_taker=quiztaker, question=question)
# 			obj.answer = answer
# 			obj.save()

# 		quiztaker.completed = True
# 		correct_answers = 0

# 		for users_answer in UsersAnswer.objects.filter(quiz_taker=quiztaker):
# 			answer = Answer.objects.get(question=users_answer.question, is_correct=True)
# 			print(answer)
# 			print(users_answer.answer)
# 			if users_answer.answer == answer:
# 				correct_answers += 1

# 		quiztaker.score = int(correct_answers / quiztaker.quiz.question_set.count() * 100)
# 		print(quiztaker.score)
# 		quiztaker.save()

# 		return Response(self.get_serializer(quiz).data)

quiz/templates/instruction.html
{% extends "all.html" %}
{% block content %}
<div class="" style="margin-top: 7%;"></div>
<div class="container">
    <h2>EXAM INSTRUCTIONS</h2>
    <h5>Steps For Accessing Your Exam Online:</h5>
    <p>Close all programs, including email</p>
    <p>Click on the Click here to open the exam link provided in the email from The College.</p>
    <p>Click "Log In For Your Exam Here" at the bottom of the screen.</p>
    <p>Have your Proctor enter the Username and Password provided in the email from The College and click enter.</p>
    <p>To begin the exam, click on the link to the appropriate exam listed under Online Assessments.</p>
    <p><h5>During the exam: </h5></p>
    <p>The student may not use his or her textbook, course notes, or receive help from a proctor or any other outside source.</p>
    <p>Students must complete the 50-question multiple-choice exam within the 75-minute time frame allotted for the exam. </p>
    <p>Students must not stop the session and then return to it. This is especially important in the online environment where the system will "time-out" and not allow the student or you to reenter the exam site.    </p>

    <p><h2>What to do if your online exam is interrupted </h2></p>
    <p>If your online exam is interrupted, click the “Back” button on your web browser to see if you can return to the exam. If not, follow the instructions below to resume taking the exam. Note: Answers are saved by the system in 10-minute intervals. If you have to log back in to complete your exam, your prior answers will be remain from the last system-save.    </p>
    <p>Reconnect to the Internet and log back into Blackboard.    </p>
    <p>Follow your original instructions to access the exam login page.</p>
    <p>Ask your proctor to re-enter the Username and Password, then select the checkbox "Show list of unfinished exams, only select to re-enter an exam already in progress." This will enable you to resume taking the exam, close to the point before the interruption occurred.    </p>
    <p>Have your Proctor enter the Username and Password provided in the email from The College and click enter.    </p>
    <p><h2>Support</h2></p>
    <p>If you have any questions, please contact the organizetion. </p>

    <a href="{% url 'quizDetail' slug %}" class="btn btn-primary my-5 btn-lg" style="text-align: center;">start quiz</a>

</div>
{% endblock content %}

quiz/templates/quiz.html
{% extends "all.html" %}

{% block content %}
<div style="padding-top:100px;">
    <h1 class="d-flex justify-content-center mx-4" style="font-family: consolas;border-style: dashed;">Available Exam</h1>
    <div class="container alert alert-success">
        
        {% for quiz in quiz_list %} 
        <a href='{% url "instruction" %}?quiz={{quiz.slug}}'>
            <h4 class="alert-heading">Paper Name : {{quiz}} <span style="float: right;" id="timer">{{quiz.timestamp_str}}</span></h24> 
                <hr style="height:4px;border:none;color:#333;background-color:#333;" /> 
                <!-- <h4>question: {{question.label}}</h4> -->
        </a>
        {% endfor %}
    </div> 
    
<h1 class="d-flex justify-content-center mx-4" style="font-family: consolas;border-style: dashed;">Given Exam</h1>
    <!-- <h1 class="container">Recent</h1> -->
    <div class="container alert alert-dark mt-3">
        {% for quiztaker in user.quiztaker_set.all %}
        <h2 class="alert-heading">{{quiztaker.quiz.name}}
            <a href="{% url 'result' quiztaker.quiz.slug %}" class="btn btn-success" style="float: right;">View Result</a>
        </h2> 
        <hr style="height:2px;border:none;color:#333;background-color:#333;" /> 
        <!-- <h4>question: {{question.label}}</h4> -->
    {% endfor %}
    </div>

</div>
{% endblock content %}
{% block script %}
<script>

</script>
{% endblock script %}

quiz/templates/quiz_detail.html
{% extends "all.html" %}

{% block style %}
<style>
    #mydiv{
        position: fixed;
        z-index: 99999999999;
        width:250px !important;
        transform: translate(5%,400%);
    }
    #mydivheader{
        cursor: move;
        width:100% !important;
    }
</style>
{% endblock style %}
{% block content %}
<!-- Draggable DIV -->
<div id="mydiv">
    <div class="pl-3 d-flex bg-primary text-light card shadow" id="mydivheader">
        <h2 id="countdown">Time : 00:00:00</h2>
    </div>
</div>
<div style="padding-top:100px;" id="secure">
    <h1 class="d-flex justify-content-center mx-4" style="font-family: consolas;border-style: dashed;">Questions</h1>
        {% for question in quiz.question_set.all %}
    <div class="container shadow my-4 py-2 card "> <br/>
        <h3>{{forloop.counter}} : {{question.label}}</h3>
        <hr style="height:1px;border:none;color:#333;background-color:#333;" />
        {% for answer in  question.answer_set.all %}
        <div class="form-check">
            <input onchange="selectIt('{{answer.id}}','{{question.id}}');" class="form-check-input  d-flex" name= "ans_{{question.id}}" type="radio" value="{{answer}}" id="defaultCheck-{{forloop.counter}}-{{question.id}}" required>
            <label class="form-check-label" for="defaultCheck-{{forloop.counter}}-{{question.id}}">
                {{answer}}  
            </label>
        </div> 
        <br>
        {% endfor %}
    </div> 
    {% endfor %}
            <div class="container">
            <form method="POST" action="{% url "saveUserAnswer" %}" id="ExamForm"  >  {% csrf_token %} 
                <input type="hidden" name = "allData" id="all-data" value = "{}"/>
                <input type="hidden" name = "quizTaker" value ="{{quiztaker.id}}"/>
                <button type="submit" class="btn btn-primary btn-lg" onclick="return confirm('Are you sure you want to submit the quiz ?')" >Submit</button>
            </form>
            </div>
        </div>




{% endblock content %}
{% block script %}
<script>
    var FileJson = new Object();
    var distinct = [];
    var el = document.getElementById("all-data");
    function selectIt(ans_id,q_id){
        if(q_id in distinct === false){
            FileJson[q_id] = ans_id
            distinct.push(q_id)
            el.value = JSON.stringify(FileJson)
        }else{
            delete FileJson[q_id];
            FileJson[q_id] = ans_id;   //Done✌✌
            el.value = JSON.stringify(FileJson)
        }
    
        
    }
    $(window).ready(()=>{
        
        var h = 0;
        var min =0;
        var sec = 1;
        window.setInterval(function set(){
            if( sec == 59){
                min = min+1;
                sec = 0;
            }
            if (min == 59){
                h = h+1;
                min = 0
            }
            timer = `Time : ${h}:${min}:${sec}`
            $("#countdown").text(timer)
            sec = sec+1
            
        },1000)
        
        // timout
        var t = "{{quiz.timestamp_str}}".split(":")
        var time = ((Number(t[0])*60+Number(t[1]))+Number(t[2]))*60000 
        window.setTimeout(function saveForm() {
            alert("Time Out")
            timer = `Time : ${00}:${00}:${00}`
            $("#countdown").text(timer)
            document.getElementById("ExamForm").submit()
        }, time);
        

    })
    // dragdrop dont touch
// Make the DIV element draggable:
dragElement(document.getElementById("mydiv"));

function dragElement(elmnt) {
  var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;
  if (document.getElementById(elmnt.id + "header")) {
    // if present, the header is where you move the DIV from:
    document.getElementById(elmnt.id + "header").onmousedown = dragMouseDown;
  } else {
    // otherwise, move the DIV from anywhere inside the DIV:
    elmnt.onmousedown = dragMouseDown;
  }

  function dragMouseDown(e) {
    e = e || window.event;
    e.preventDefault();
    // get the mouse cursor position at startup:
    pos3 = e.clientX;
    pos4 = e.clientY;
    document.onmouseup = closeDragElement;
    // call a function whenever the cursor moves:
    document.onmousemove = elementDrag;
  }

  function elementDrag(e) {
    e = e || window.event;
    e.preventDefault();
    // calculate the new cursor position:
    pos1 = pos3 - e.clientX;
    pos2 = pos4 - e.clientY;
    pos3 = e.clientX;
    pos4 = e.clientY;
    // set the element's new position:
    elmnt.style.top = (elmnt.offsetTop - pos2) + "px";
    elmnt.style.left = (elmnt.offsetLeft - pos1) + "px";
  }

  function closeDragElement() {
    // stop moving when mouse button is released:
    document.onmouseup = null;
    document.onmousemove = null;
  }
}
// end

</script>
{% endblock script %}
 

quiz/templates/result.html
{% extends "all.html" %}

{% block content %}
<section class="
{% if is_pass %}
    bg-success
{% else %}
    bg-danger
{% endif %}
"> 

    <div style="padding-top:150px;min-height:500px;padding-bottom: 150px    ;" class="container">
        <div class="card shadow text-center p-5" style="border:2px dotted rgb(0, 56, 0)!important;">
            
            <div>
            {% if is_pass %}
                <span class="material-icons text-success" style="font-size: 100px;">
                    sentiment_very_satisfied
                </span>
            {% else %}
                <span class="material-icons text-danger" style="font-size: 100px;">
                    sentiment_very_dissatisfied
                </span>
            {% endif %}
        </div>
        <h1>Marks : <span class="text-danger">{{quiz_taker.score}}</span> %</h1>
        
        <div style="font-size: 60px;font-family: comic sans ms;" >
            {% if is_pass %}
            PASS !!
            {% else %}
            FAIL !!
            {% endif %}
        </div>
    </div>
    <!-- 
        <div class="container alert
    
    ">
    
    <h2 class="alert-heading">Marks : {{quiz_taker.score}}% <span style="float: right;">
        {% if is_pass %}
        Pass
        {% else %}
        Fail
        {% endif %}
        
    </span></h2> 
    <hr style="height:4px;border:none;color:#333;background-color:#333;" /> 
    
</div>  -->
</div>
<!-- <h4>question: {{question.label}}</h4> -->
</section>

{% endblock content %}
{% block script %}
<script>
</script>
{% endblock script %}